site_name: FactFiber.ai Documentation Portal
site_description: Centralized documentation hub for FactFiber.ai projects and systems
site_url: https://docs.factfiber.ai

repo_name: factfiber/factfiber-ai-docs
repo_url: https://github.com/factfiber/factfiber-ai-docs
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.action.edit
    - content.tooltips
    - content.tabs.link
    - toc.follow
  # logo: assets/images/factfiber-logo.svg
  # favicon: assets/images/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra_css:
#   - assets/css/extra.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/factfiber
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/factfiber
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      temp_dir: tmp/mkdocs-multirepo
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'default'
      javascript: https://unpkg.com/mermaid/dist/mermaid.min.js
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

nav:
  - Home: index.md

  - User Guide:
      - guide/index.md
      - Getting Started: guide/getting-started.md
      - Architecture: guide/architecture.md
      - Development: guide/development.md
      - Documentation Standards: guide/documentation_standards.md
      - Documentation Organization: guide/documentation_organization.md
      - Repository Onboarding: guide/repository_onboarding.md

  - Projects:
      - Overview: projects/index.md
      - "Timbuktu": "!import https://github.com/factfiber/timbuktu.git?branch=main&docs_dir=docs/*"

  - API Reference:
      - FastAPI Documentation: api/index.md

  - Technical Reference:
      - reference/index.md
      - Components:
          - ff_docs Package: reference/components/ff_docs/index.md
      - Code Reference: reference/code/index.html

  - Development:
      - Getting Started: dev/getting-started.md
      - Contributing: dev/contributing.md
      - Architecture: dev/architecture.md
      - DevSpace Guide: dev/devspace-guide.md

watch:
  - src/
  - docs/

# Additional configuration
strict: false             # Don't fail build on warnings (imported repos may have issues)
use_directory_urls: true  # Pretty URLs
