apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: ff-docs-dev
  labels:
    app: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: factfiber-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/component: authentication
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4180
          protocol: TCP
        - name: metrics
          containerPort: 44180
          protocol: TCP
        env:
        # Basic configuration
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: "0.0.0.0:4180"
        - name: OAUTH2_PROXY_METRICS_ADDRESS
          value: "0.0.0.0:44180"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://ff-docs-app:8000/"

        # Provider configuration (GitHub)
        - name: OAUTH2_PROXY_PROVIDER
          value: "github"
        - name: OAUTH2_PROXY_GITHUB_ORG
          value: "factfiber"
        - name: OAUTH2_PROXY_GITHUB_TEAM
          value: "docs-team,platform-team,admin-team"

        # Session configuration
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: "false"  # Set to true for HTTPS
        - name: OAUTH2_PROXY_COOKIE_SAMESITE
          value: "lax"
        - name: OAUTH2_PROXY_COOKIE_HTTPONLY
          value: "true"
        - name: OAUTH2_PROXY_COOKIE_NAME
          value: "_oauth2_proxy_ff_docs"

        # Headers for downstream services
        - name: OAUTH2_PROXY_SET_XAUTHREQUEST
          value: "true"
        - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
          value: "true"
        - name: OAUTH2_PROXY_PASS_USER_HEADERS
          value: "true"

        # Development settings
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"  # Allow any email domain in development
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "false"

        # Secrets from environment
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: client-id
              optional: true
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: client-secret
              optional: true
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: cookie-secret
              optional: true

        # Health checks
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5

        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Security context
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
