apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-docs-app
  namespace: ff-docs-dev
  labels:
    app: ff-docs
    app.kubernetes.io/name: ff-docs
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: factfiber-docs
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-docs
  template:
    metadata:
      labels:
        app: ff-docs
        app.kubernetes.io/name: ff-docs
        app.kubernetes.io/component: application
    spec:
      containers:
      - name: ff-docs
        image: ghcr.io/factfiber/ff-docs:dev-latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: mkdocs
          containerPort: 8001
          protocol: TCP
        env:
        # Configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: LOG_LEVEL
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: SERVER_HOST
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: SERVER_PORT
        - name: SERVER_RELOAD
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: SERVER_RELOAD
        - name: MKDOCS_SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: MKDOCS_SITE_NAME
        - name: MKDOCS_SITE_URL
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: MKDOCS_SITE_URL
        - name: MKDOCS_TEMP_DIR
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: MKDOCS_TEMP_DIR
        - name: GITHUB_ORG
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: GITHUB_ORG
        - name: GITHUB_API_URL
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: GITHUB_API_URL
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: ff-docs-config
              key: CORS_ORIGINS
        # Secrets
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: ff-docs-secrets
              key: github-token
              optional: true
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ff-docs-secrets
              key: jwt-secret-key
        - name: OAUTH2_PROXY_SECRET
          valueFrom:
            secretKeyRef:
              name: ff-docs-secrets
              key: oauth2-proxy-secret
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: ff-docs-secrets
              key: webhook-secret
        # Health checks
        livenessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        # Resource management
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Volume mounts for development
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp/ff-docs
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: temp-storage
        emptyDir: {}
      - name: app-logs
        emptyDir: {}
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      # Service account
      serviceAccountName: default