apiVersion: v1
kind: Namespace
metadata:
  name: ff-docs-dev
  labels:
    app.kubernetes.io/name: ff-docs
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: factfiber-docs
    environment: development