apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: ff-docs-dev
  labels:
    app: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: authentication
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4180
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 44180
    targetPort: metrics
    protocol: TCP
  selector:
    app: oauth2-proxy