// Lambda@Edge Configuration
// This file is generated by Terraform and contains configuration for the authentication function

const CONFIG = {
  // GitHub OAuth Configuration
  GITHUB_CLIENT_ID: '${github_client_id}',
  GITHUB_CLIENT_SECRET: '${github_client_secret}',
  GITHUB_ORG: '${github_org}',

  // Access Control
  ALLOWED_TEAMS: ${allowed_teams},
  PUBLIC_PATHS: ${public_paths},

  // JWT Configuration
  JWT_SECRET: '${jwt_secret}',
  COOKIE_DOMAIN: '${cookie_domain}',

  // Environment
  ENVIRONMENT: '${environment}',

  // GitHub API URLs
  GITHUB_API_BASE: 'https://api.github.com',
  GITHUB_OAUTH_BASE: 'https://github.com/login/oauth',

  // Cookie Settings
  COOKIE_NAME: 'factfiber-docs-auth',
  COOKIE_MAX_AGE: 24 * 60 * 60, // 24 hours in seconds

  // JWT Settings
  JWT_EXPIRES_IN: '24h',
  JWT_ALGORITHM: 'HS256'
};

// Export for use in Lambda function
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}

// Also make available as global for compatibility
if (typeof global !== 'undefined') {
  global.LAMBDA_CONFIG = CONFIG;
}
